export const AppConstant = {
  "SAVE_USER_DETAILS_REQUEST":"SAVE_USER_DETAILS_REQUEST",
  "SAVE_USER_DETAILS_SUCCESS":"SAVE_USER_DETAILS_SUCCESS",
  "SAVE_USER_DETAILS_FAIL":"SAVE_USER_DETAILS_FAIL",
};

